# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: windows.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='windows.proto',
  package='windows',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rwindows.proto\x12\x07windows\"(\n\x0bWindowState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\t\"2\n\nAllWindows\x12$\n\x06window\x18\x01 \x03(\x0b\x32\x14.windows.WindowState\"\x06\n\x04void2|\n\x0eWindowsService\x12\x36\n\x08\x64oWindow\x12\x14.windows.WindowState\x1a\x14.windows.WindowState\x12\x32\n\x0c\x63heckWindows\x12\r.windows.void\x1a\x13.windows.AllWindowsb\x06proto3'
)




_WINDOWSTATE = _descriptor.Descriptor(
  name='WindowState',
  full_name='windows.WindowState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='windows.WindowState.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='windows.WindowState.state', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=66,
)


_ALLWINDOWS = _descriptor.Descriptor(
  name='AllWindows',
  full_name='windows.AllWindows',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='window', full_name='windows.AllWindows.window', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=118,
)


_VOID = _descriptor.Descriptor(
  name='void',
  full_name='windows.void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=126,
)

_ALLWINDOWS.fields_by_name['window'].message_type = _WINDOWSTATE
DESCRIPTOR.message_types_by_name['WindowState'] = _WINDOWSTATE
DESCRIPTOR.message_types_by_name['AllWindows'] = _ALLWINDOWS
DESCRIPTOR.message_types_by_name['void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WindowState = _reflection.GeneratedProtocolMessageType('WindowState', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWSTATE,
  '__module__' : 'windows_pb2'
  # @@protoc_insertion_point(class_scope:windows.WindowState)
  })
_sym_db.RegisterMessage(WindowState)

AllWindows = _reflection.GeneratedProtocolMessageType('AllWindows', (_message.Message,), {
  'DESCRIPTOR' : _ALLWINDOWS,
  '__module__' : 'windows_pb2'
  # @@protoc_insertion_point(class_scope:windows.AllWindows)
  })
_sym_db.RegisterMessage(AllWindows)

void = _reflection.GeneratedProtocolMessageType('void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'windows_pb2'
  # @@protoc_insertion_point(class_scope:windows.void)
  })
_sym_db.RegisterMessage(void)



_WINDOWSSERVICE = _descriptor.ServiceDescriptor(
  name='WindowsService',
  full_name='windows.WindowsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=128,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='doWindow',
    full_name='windows.WindowsService.doWindow',
    index=0,
    containing_service=None,
    input_type=_WINDOWSTATE,
    output_type=_WINDOWSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='checkWindows',
    full_name='windows.WindowsService.checkWindows',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_ALLWINDOWS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WINDOWSSERVICE)

DESCRIPTOR.services_by_name['WindowsService'] = _WINDOWSSERVICE

# @@protoc_insertion_point(module_scope)
