# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import windows_pb2 as windows__pb2


class WindowsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doWindow = channel.unary_unary(
                '/windows.WindowsService/doWindow',
                request_serializer=windows__pb2.WindowState.SerializeToString,
                response_deserializer=windows__pb2.WindowState.FromString,
                )
        self.checkWindows = channel.unary_unary(
                '/windows.WindowsService/checkWindows',
                request_serializer=windows__pb2.void.SerializeToString,
                response_deserializer=windows__pb2.AllWindows.FromString,
                )


class WindowsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def doWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def checkWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WindowsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.doWindow,
                    request_deserializer=windows__pb2.WindowState.FromString,
                    response_serializer=windows__pb2.WindowState.SerializeToString,
            ),
            'checkWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.checkWindows,
                    request_deserializer=windows__pb2.void.FromString,
                    response_serializer=windows__pb2.AllWindows.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'windows.WindowsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WindowsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/windows.WindowsService/doWindow',
            windows__pb2.WindowState.SerializeToString,
            windows__pb2.WindowState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def checkWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/windows.WindowsService/checkWindows',
            windows__pb2.void.SerializeToString,
            windows__pb2.AllWindows.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
